Adds an entrypoint for use by JUnit infrastructure
McModLauncher/bootstraplauncher pull request #13
Opened 2023-12-23 10:38 UTC by shartte

Depends on https://github.com/McModLauncher/securejarhandler/pull/60

The goal is to add a new entrypoint to BSL for JUnit runners, which disables classloader isolation. This change adds that entrypoint. It is intentionally called `testMain` to prevent it from being used accidentally via the command-line.

This is used to allow test-classes to live in the GAME layer, while still loading JUnit and other testing library classes found on the normal classpath. When being run by a unit testing framework, we do not control the JVM entrypoint like we normally do, and Gradle for example will class-load JUnit before calling any other hook. Our test classes need to refer to those same loaded classes, making it easier if isolation is disabled in such scenarios.

2024-01-09 07:29 UTC, marchermans requested changes
I have thought about this for a while.

Allthough I am convinced that the JUnit API provides other, more standardized, ways of doing testing in a modularly isolated environment, right now we do not have the time.

As such this is at least a bridge and a gap to allow for this to work.

However, since I want to be clear that this should not be used in production, what so ever, I want a very load warning in the source code, in the form of previously mentioned annotations and documentation. As well as, a very loud warning in a log file!

Please add those and then this is good.

2024-01-09 07:29 UTC, marchermans commented on src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java
> +    public static void testMain(String... args) {
Add an @VisibleForTesting annotation, add documentation indicating that this is not supposed to be used in production.

2024-01-14 20:43 UTC, pupnewfster commented on src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java
> +    public static void unitTestingMain(String... args) {
Should this method have some javadocs similar to the ones that got added to the SJH PR? Rather than only having it as a log (have a log plus javadocs warning against using this for random purposes)

2024-01-15 02:52 UTC, pupnewfster commented on src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java
> +    public static void unitTestingMain(String... args) {
Doesn't hurt to have both, though I agree it is mostly self-explanatory

2024-01-20 19:15 UTC, marchermans approved these changes

2024-01-20 19:15 UTC, merged